name: ground_z
description: Gamebook in a mobile app format with music and images.

publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  just_audio: ^0.9.24
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "lib/assets/Logo_slang_squarefondo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/text/
    - assets/drawings/
    - assets/fonts/
    - assets/icons/
    - assets/music/

  fonts:
    - family: Cuomotype-Regular
      fonts:
        - asset: assets/fonts/cuomotype.ttf
    - family: JD Irregutype
      fonts:
        - asset: assets/fonts/JdIrregutype.ttf
